sudo: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
- script: nosetests --with-coverage --cover-package=app && coverage report
after_success:
  -coveralls
